# Generated by Django 4.2.3 on 2025-09-09 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionsDetail', models.TextField()),
                ('contactList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.contactlist')),
            ],
        ),
    ]
