# Generated by Django 4.2.3 on 2025-09-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_product_picture_product_specfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specfile',
            field=models.FileField(blank=True, null=True, upload_to='specfiles/'),
        ),
    ]
