# Generated by Django 4.2.3 on 2025-09-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_product_picture_alter_product_specfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specfile',
            field=models.FileField(blank=True, null=True, upload_to='specfile/'),
        ),
    ]
