# Generated by Django 4.2.3 on 2025-10-28 07:23

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_product_picture_alter_product_specfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('ride_date', models.DateField()),
                ('ride_time', models.CharField(blank=True, choices=[('morning', 'Morning'), ('noon', 'Noon'), ('afternoon', 'Afternoon')], max_length=10)),
                ('pickup_place', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_type', models.CharField(choices=[('rider', 'Rider'), ('passenger', 'Passenger')], max_length=20)),
                ('age_group', models.CharField(choices=[('adult', 'Adult'), ('child', 'Child')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.booking')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_items', to='myapp.program')),
            ],
            options={
                'ordering': ['booking_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_type', models.CharField(choices=[('rider', 'Rider'), ('passenger', 'Passenger')], max_length=20)),
                ('age_group', models.CharField(choices=[('adult', 'Adult'), ('child', 'Child')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='myapp.program')),
            ],
            options={
                'ordering': ['program__code', 'participant_type', 'age_group'],
                'unique_together': {('program', 'participant_type', 'age_group')},
            },
        ),
    ]
