# Generated by Django 4.2.3 on 2025-10-29 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_booking_program_bookingitem_programrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BookingAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_addons', to='myapp.addon')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='myapp.booking')),
            ],
            options={
                'ordering': ['booking_id', 'id'],
            },
        ),
    ]
