# Generated by Django 4.2.3 on 2025-10-29 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_addon_bookingaddon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='programs/')),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.program')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
