# Generated by Django 4.2.3 on 2025-10-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_programimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='itinerary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='pricing_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='schedule_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='tour_excludes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='tour_includes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='tour_notes',
            field=models.TextField(blank=True),
        ),
    ]
