# Generated by Django 4.2.3 on 2025-10-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_fill_program_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=60)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('likes', models.TextField(blank=True)),
                ('dislikes', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, upload_to='staff/')),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
