# Generated by Django 4.2.3 on 2025-11-25 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_bike_bikeassignment'),
    ]

    def seed_bikes(apps, schema_editor):
        Bike = apps.get_model('myapp', 'Bike')
        for number in range(1, 51):
            Bike.objects.get_or_create(number=number)

    def remove_bikes(apps, schema_editor):
        Bike = apps.get_model('myapp', 'Bike')
        Bike.objects.filter(number__lte=50).delete()

    operations = [
        migrations.RunPython(seed_bikes, remove_bikes),
    ]
